name: Build and Push Docker Image

on: [push, pull_request]

jobs:
  build-and-push:
    environment: django-dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: messaging_app/
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/messaging_app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/messaging_app:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/messaging_app:latest,mode=max