name: messaging-app

services:
  web:
    image: royalboe/messaging-app:v2
    build: 
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile to use for building the image
    container_name: messaging_app_web
    volumes: 
      - .:/app  # Mount the current directory to /app in the container
    working_dir: /app  # Set the working directory to /app
    command: python3 manage.py runserver 0.0.0.0:8000  # Ensure it runs with python3 as per the requirement
    ports:
      - "9000:8000"  # Expose port 8000 for the Django app
    depends_on:
      - db  # Ensure that the db service starts before the web service
    env_file:
      - .env  # The database hostname should be the service name (db)

  db:
    image: mysql:8.0  # Using MySQL 8.0 version
    container_name: messaging_app_db
    ports:
      - "3306:3306"  # Expose port 3306 for MySQL
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}  # The default database for your Django app


volumes:  
  db_data:  # Uncomment if you want to persist MySQL data